#!/usr/bin/env bash

cat *.words | \
	tr '[:upper:]' '[:lower:]' | \
	tr ' ' '\n' | \
	sed 's/\.//' | \
	sed 's_\\/__' | \
	sed '/^[0-9]/d' | \
	sed '/http:/d' | \
	sed '/https:/d' | \
	sed 's/\,//' | \
	sed 's/\&quot;//g' | \
	sed 's/\&amp;//g' | \
	sed 's/>/\n>/g' | \
	sed 's/<span//g' | \
	sed 's/\?//g' | \
	sed 's/\&lt;//g' \
	> all.dat						

